{% set python_min = "3.10" %}
{% set name = "plotastrodata" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plotastrodata-{{ version }}.tar.gz
  sha256: dd6614ea1fd5be71ae5c6099d387191b34e9eba87a93223c171f6482ae9e4770

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - astropy-base
    - matplotlib-base
    - ptemcee
    - corner

test:
  imports:
    - plotastrodata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yusukeaso-astron/plotastrodata
  summary: plotastrodata can be used mainly to make figures from FITS files, as well as other analyses in astronomy.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yusukeaso-astron
