{% set python_min = "3.10" %}
{% set name = "plotastrodata" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plotastrodata-{{ version }}.tar.gz
  sha256: 2af17698feadc5d483e24c7e4413f42cabd61ea9a1ae9a59343e748fe8b15f2d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - astropy-base
    - corner
    - dynesty
    - matplotlib-base
    - multiprocess
    - numpy
    - pillow
    - plotly
    - ptemcee
    - scikit-image
    - scipy
    - tqdm

test:
  imports:
    - plotastrodata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yusukeaso-astron/plotastrodata
  summary: plotastrodata is a tool for astronomers to create figures from FITS files and perform fundamental data analyses with ease.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yusukeaso-astron
